// Gain Stage — Overdrive/Distortion via waveshaping LUT
// Signal flow: Input -> Upsample(4x) -> Pre-gain -> LUT waveshape -> Post-gain -> Downsample(4x)
// Oversampling prevents aliasing from harmonics generated by nonlinear clipping

module gain_stage #(
    parameter DATA_WIDTH      = 24,
    parameter TABLE_ADDR_WIDTH = 10,   // 2^10 = 1024-entry waveshaping LUT
    parameter TABLE_WIDTH     = 16,    // LUT output precision
    parameter NUM_CURVES      = 5,     // Selectable waveshaping curves
    parameter OVERSAMPLE      = 4,     // Oversampling factor
    parameter PRE_GAIN_WIDTH  = 16,    // Drive knob resolution
    parameter INTERP          = 1      // Linear interpolation between LUT entries
)(
    input  wire                          clk,
    input  wire                          rst,

    // AXI-Stream input
    input  wire signed [DATA_WIDTH-1:0]  s_axis_tdata,
    input  wire                          s_axis_tvalid,
    output wire                          s_axis_tready,
    input  wire                          s_axis_tlast,

    // AXI-Stream output
    output reg  signed [DATA_WIDTH-1:0]  m_axis_tdata,
    output reg                           m_axis_tvalid,
    input  wire                          m_axis_tready,
    output reg                           m_axis_tlast,

    // Control
    input  wire [PRE_GAIN_WIDTH-1:0]     drive,       // Pre-gain amount
    input  wire [PRE_GAIN_WIDTH-1:0]     level,       // Output level
    input  wire [$clog2(NUM_CURVES)-1:0] curve_sel    // Waveshape selection
);

    localparam TABLE_DEPTH = 1 << TABLE_ADDR_WIDTH;
    localparam PROD_WIDTH = DATA_WIDTH + PRE_GAIN_WIDTH;

    // Waveshaping LUT (one per curve, addressed by signal amplitude)
    // Input range [-1, 1] mapped to address [0, TABLE_DEPTH-1]
    reg signed [TABLE_WIDTH-1:0] wave_lut [0:NUM_CURVES*TABLE_DEPTH-1];

    // Initialize LUTs (placeholder — real values from gen_waveshape_lut.py)
    integer lut_i;
    initial begin
        for (lut_i = 0; lut_i < NUM_CURVES * TABLE_DEPTH; lut_i = lut_i + 1)
            wave_lut[lut_i] = 0;
    end

    // State machine
    localparam ST_IDLE     = 0;
    localparam ST_UPSAMPLE = 1;
    localparam ST_PROCESS  = 2;
    localparam ST_DOWNSAMPLE = 3;

    reg [1:0] state;
    reg [$clog2(OVERSAMPLE)-1:0] os_count;
    reg signed [DATA_WIDTH-1:0] input_sample;
    reg signed [DATA_WIDTH-1:0] prev_sample;
    reg last_saved;

    // Interpolated oversampled sample
    reg signed [DATA_WIDTH-1:0] os_sample;

    // Processing pipeline
    reg signed [PROD_WIDTH-1:0] gained_sample;
    reg signed [DATA_WIDTH-1:0] lut_output;
    reg signed [PROD_WIDTH-1:0] leveled_output;

    // Accumulator for downsampling (simple averaging)
    reg signed [DATA_WIDTH+$clog2(OVERSAMPLE)-1:0] downsample_acc;

    // Working registers for processing pipeline
    reg signed [DATA_WIDTH:0] diff;
    reg [TABLE_ADDR_WIDTH-1:0] lut_addr;
    reg signed [DATA_WIDTH-1:0] clipped;

    assign s_axis_tready = (state == ST_IDLE) && (m_axis_tready || !m_axis_tvalid);

    always @(posedge clk) begin
        if (rst) begin
            state <= ST_IDLE;
            os_count <= 0;
            input_sample <= 0;
            prev_sample <= 0;
            m_axis_tdata <= 0;
            m_axis_tvalid <= 0;
            m_axis_tlast <= 0;
            downsample_acc <= 0;
            last_saved <= 0;
        end else begin
            case (state)
                ST_IDLE: begin
                    if (m_axis_tvalid && m_axis_tready)
                        m_axis_tvalid <= 0;

                    if (s_axis_tvalid && s_axis_tready) begin
                        prev_sample <= input_sample;
                        input_sample <= s_axis_tdata;
                        last_saved <= s_axis_tlast;
                        state <= ST_UPSAMPLE;
                        os_count <= 0;
                        downsample_acc <= 0;
                    end
                end

                ST_UPSAMPLE: begin
                    // Linear interpolation between prev and current for oversampled points
                    // os_sample = prev + (current - prev) * os_count / OVERSAMPLE
                    diff = input_sample - prev_sample;
                    os_sample <= prev_sample + ((diff * os_count) / OVERSAMPLE);
                    state <= ST_PROCESS;
                end

                ST_PROCESS: begin
                    // Apply pre-gain (drive)
                    gained_sample = os_sample * $signed({1'b0, drive});

                    // Map gained sample to LUT address
                    // Gained sample is in Q format — use MSBs as address

                    // Saturate to LUT range
                    if (gained_sample[PROD_WIDTH-1:PROD_WIDTH-2] == 2'b01)
                        clipped = {1'b0, {(DATA_WIDTH-1){1'b1}}};  // Max positive
                    else if (gained_sample[PROD_WIDTH-1:PROD_WIDTH-2] == 2'b10)
                        clipped = {1'b1, {(DATA_WIDTH-1){1'b0}}};  // Max negative
                    else
                        clipped = gained_sample[PRE_GAIN_WIDTH +: DATA_WIDTH];

                    // Convert signed to unsigned LUT address: offset by half
                    lut_addr = clipped[DATA_WIDTH-1:DATA_WIDTH-TABLE_ADDR_WIDTH] + (TABLE_DEPTH / 2);

                    // LUT lookup with curve selection
                    lut_output <= wave_lut[curve_sel * TABLE_DEPTH + lut_addr];

                    // Apply output level
                    leveled_output = lut_output * $signed({1'b0, level});

                    // Accumulate for downsampling
                    downsample_acc <= downsample_acc + leveled_output[PRE_GAIN_WIDTH +: DATA_WIDTH];

                    if (os_count == OVERSAMPLE - 1) begin
                        state <= ST_DOWNSAMPLE;
                    end else begin
                        os_count <= os_count + 1;
                        state <= ST_UPSAMPLE;
                    end
                end

                ST_DOWNSAMPLE: begin
                    // Average the oversampled results
                    m_axis_tdata <= downsample_acc >>> $clog2(OVERSAMPLE);
                    m_axis_tvalid <= 1;
                    m_axis_tlast <= last_saved;
                    state <= ST_IDLE;
                end
            endcase
        end
    end

endmodule
